#!/bin/bash
echo "bash - post checkout hook activated"
echo "[post-checkout hook: $1 $2 $3]"
# post-checkout hook that update submodules

# Get the directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

prev_HEAD="$1"
new_HEAD="$2"
new_branch="$3"

if [ $prev_HEAD != $new_HEAD ]; then
   source $DIR/venv
   bldr deps.get
   git clean -f -f -d
fi

exit 0