#!/bin/bash
echo "[post-rewrite hook: $1]"

# Get the directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

# quick script to call "git submodule update" automatically if the
# .dependency.lock.toml file is changed

changedfiles=( `git diff-tree --no-commit-id --name-only HEAD@{1} HEAD` )

if [[ "${changedfiles[*]}" =~ ".dependency.lock.toml" ]]; then
    echo "initializing & updating submodule(s)"
    source $DIR/venv
    
    # Use the provided venv
    source $DIR/venv
    bldr deps.get
fi