#!/bin/sh
echo "[post-rewrite hook: $1]"

# quick script to call "git submodule update" automatically if the
# .gitmodules file is changed

changedfiles=( `git diff-tree --no-commit-id --name-only HEAD@{1} HEAD` )

if [[ "${changedfiles[*]}" =~ ".dependency.lock.toml" ]]; then
    echo "initializing & updating submodule(s)"
    bldr dep.sync
fi