#!/bin/bash
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# if git rev-parse --verify HEAD >/dev/null 2>&1
# then
# 	against=HEAD
# else
# 	# Initial commit: diff against an empty tree object
# 	against=$(git hash-object -t tree /dev/null)
# fi


# # If there are whitespace errors, print the offending file names and fail.
# exec git diff-index --check --cached $against --
#echo "pre-commit $PWD"
# Get the directory of this script
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

#source $DIR/venv
#bldr deps.lock --staged